# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: ./target/untitled-1.0-SNAPSHOT.jar

  docker-build:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: build
        path: ./
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Container image
      run: docker build -t valerahex/demoapp:latest .
    - name: Publish Docker image
      run: docker push valerahex/demoapp:latest


  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [ docker-build ]

    steps:
      - uses: actions/checkout@v2

      - uses: WyriHaximus/github-action-helm3@v2
        name: Deploy
        with:
          exec: helm upgrade -i -f ./helm/demoapp/values.yaml demoapp ./helm/demoapp 
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          
  send-telegram:
    name: Send to Telegram
    runs-on: ubuntu-latest
    needs: [ build ]
    
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build
          path: ./
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ./untitled-1.0-SNAPSHOT.jar
          
